# Etapa 1: construir la app Angular
FROM node:20-alpine AS build
WORKDIR /usr/src/app
RUN npm install -g @angular/cli
COPY app/package*.json ./
RUN npm install
COPY app/ .



# # Etapa 1: construir la app Angular
# FROM node:20-alpine AS build
#
# WORKDIR /usr/src/app
#
# # Instalar Angular CLI
# RUN npm install -g @angular/cli
#
# # Copiar package.json y lock
# COPY app/package*.json ./
#
# # Instalar dependencias
# RUN npm install
#
# # Copiar el resto del código
# COPY app/ .
#
# # Construir la app en modo producción
# RUN ng build --configuration production
#
# # Etapa 2: contenedor liviano solo con los archivos estáticos
# FROM alpine:3.20
#
# WORKDIR /usr/share/solarweb
#
# # Copiar los archivos de Angular ya compilados
# COPY --from=build /usr/src/app/dist/app ./
#
# # este contenedor solo contiene los archivos estáticos, no se encarga de desplegar
# CMD ["sh", "-c", "echo 'Build listo en /usr/share/solarweb' && sleep infinity"]
#
