services:
  # Databases
  influxdb:
    image: influxdb:2.7
    container_name: influxdb-solarweb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - /mnt/e/influx:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASS}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
      - DOCKER_INFLUXDB_INIT_RETENTION=0

  minio:
    image: minio/minio:latest
    container_name: minio-solarweb
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: "${MINIO_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_PASSWORD}"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /mnt/e/minio:/data
    command: server /data --console-address ":9001"

  # Uploaders
  minio-uploader:
    build:
      context: ./databases/minio/upload
      dockerfile: Dockerfile
    container_name: minio-uploader-solarweb
    restart: unless-stopped
    environment:
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
      - PYTHONUNBUFFERED=1
    volumes:
      - ${MINIO_UPLOAD_IMAGES_DIR}:/app/images
    depends_on:
      - minio

  influxdb-uploader:
    build:
      context: ./databases/influxdb
      dockerfile: Dockerfile
    container_name: influxdb-uploader-solarweb
    restart: unless-stopped
    environment:
      - INFLUX_ENDPOINT=${INFLUX_ENDPOINT}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
      - PYTHONUNBUFFERED=1
    volumes:
      - ${INFLUXDB_UPLOAD_CSV_DIR}:/datos
    depends_on:
      - influxdb

  zerotier:
    image: zyclonite/zerotier:latest
    container_name: zerotier-solarweb
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - zerotier-data:/var/lib/zerotier-one
    environment:
      - ZT_NETWORK_ID=${ZT_NETWORK_ID}
    entrypoint: >
      sh -c "
        /usr/sbin/zerotier-one -d &&
        echo 'Esperando a que el daemon se inicie...' &&
        sleep 8 &&
        zerotier-cli join ${ZT_NETWORK_ID} &&
        echo 'Unido a la red ${ZT_NETWORK_ID}, esperando...' &&
        tail -f /dev/null
      "

volumes:
  zerotier-data: