services:
  # ==========================================
  # BASE DE DATOS (Postgres)
  # ==========================================
  database-solarweb:
    image: postgres:16
    container_name: grupo2_solarweb_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
      PGPORT: ${POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
      - ./databases/postgres/db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - red_taller_software
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "org.uach.group=grupo2"
      - "org.uach.project=solarweb"
      - "org.uach.service=database"
      - "logging=portmail" 
  # ==========================================
  # BACKEND (FastAPI)
  # ==========================================
  backend-solarweb:
    environment:
      POSTGRES_HOST: database-solarweb
    build:
      context: ./backend
      dockerfile: Dockerfile-production
    container_name: grupo2_solarweb_backend
    restart: unless-stopped
    expose:
      - "4002"
    depends_on:
      - database-solarweb
    networks:
      - red_taller_software
    volumes:
      - ./.env:/app/backend/.env
      - zerotier-data:/var/lib/zerotier-one
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "700M"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "org.uach.group=grupo2"
      - "org.uach.project=solarweb"
      - "org.uach.service=backend"
      - "logging=portmail" 
  # ==========================================
  # FRONTEND (Angular)
  # ==========================================
  frontend-solarweb:
    build:
      context: ./frontend
      dockerfile: Dockerfile-production
    container_name: grupo2_solarweb_frontend
    restart: unless-stopped
    ports:
      - "3002:80"
    networks:
      - red_taller_software
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "400M"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "org.uach.group=grupo2"
      - "org.uach.project=solarweb"
      - "org.uach.service=frontend"
      - "logging=portmail" 
    
volumes:
  zerotier-data:
  db_data:

# Configuracion de red
networks:
  red_taller_software:
    external: false
