services:
  frontend-solarweb-production:
    build:
      context: ./frontend
      dockerfile: Dockerfile-production
    container_name: frontend-solarweb
    # SOLO PARA DEBUG
    # ports:
    #   - "3002:80"
    restart: unless-stopped
    volumes:
      - ./frontend/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - red_taller_software

  backend-solarweb:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-solarweb
    # SOLO PARA DEBUG
    # ports:
    #   - "4002:4002"
    volumes:
      - ./.env:/app/backend/.env
    env_file:
      - .env
    networks:
      - red_taller_software
    
  postgres:
    image: postgres:16
    container_name: postgres-solarweb
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
      PGPORT: 5002
    ports:
      - "5002:5002"
    volumes:
      - postgresdb:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p 5002"]
      interval: 5s
      timeout: 5s
      retries: 20
    
volumes:
  postgresdb:


# Configuracion de red
networks:
  red_taller_software:
    external: true