services:
  # ==========================================
  # FRONTEND (Angular)
  # ==========================================
  frontend-solarweb:
    profiles: ["deploy"]
    build:
      context: ./frontend
      dockerfile: Dockerfile-development
    container_name: frontend-solarweb
    ports:
      - "3002:3002"
    restart: unless-stopped
    environment:
      - TZ=America/Santiago 
    env_file:
      - .env
    depends_on:
      - backend-solarweb
    volumes:
      - ./frontend/app:/usr/src/app
      - /usr/src/app/node_modules
  # ==========================================
  # BACKEND (FastAPI)
  # ==========================================
  backend-solarweb:
    profiles: ["deploy"]
    build:
      context: ./backend
      dockerfile: Dockerfile-development
    container_name: backend-solarweb
    ports:
      - "4002:4002"
    volumes: 
      - ./backend:/app/backend
      - ./.env:/app/backend/.env
    env_file:
      - .env
    environment:
      - TZ=America/Santiago 
    depends_on:
      - postgres-solarweb
      - zerotier-solarweb
  # ==========================================
  # INFLUXDB (Time series database)
  # ==========================================
  influxdb-solarweb:
    profiles: ["data"]
    image: influxdb:2.7
    container_name: influxdb-solarweb
    ports:
      - "8086:8086"
    volumes:
      - influxdb2:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASS}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
      - DOCKER_INFLUXDB_INIT_RETENTION=0
  # ==========================================
  # MINIO (Object storage)
  # ==========================================
  minio-solarweb:
    profiles: ["data"]
    image: minio/minio:latest
    container_name: minio-solarweb
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: "${MINIO_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_PASSWORD}"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodb2:/data
    command: server /data --console-address ":9001"
  # ==========================================
  # POSTGRES (Relational database)
  # ==========================================
  postgres-solarweb:
    profiles: ["data", "deploy"]
    image: postgres:16
    container_name: postgres-solarweb
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: America/Santiago
    ports:
      - "5432:5432"
    volumes:
      - postgresdb:/var/lib/postgresql/data/pgdata
      - ./databases/postgres/db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20
  # ==========================================
  # Minio Uploader (Images)
  # ==========================================
  minio-uploader-solarweb:
    profiles: ["data"]
    build:
      context: ./databases/minio/upload
      dockerfile: Dockerfile
    container_name: minio-uploader-solarweb
    environment:
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
      - PYTHONUNBUFFERED=1
    volumes:
      - ${MINIO_UPLOAD_LOG_FILE}:/app/logs/UPLOAD_LOG.csv
      - ${MINIO_UPLOAD_IMAGES_DIR}:/app/images
    depends_on:
      - minio-solarweb
  # ==========================================
  # Influxdb uploader (CSV)
  # ==========================================
  influxdb-uploader-solarweb:
    profiles: ["data"]
    build:
      context: ./databases/influxdb
      dockerfile: Dockerfile
    container_name: influxdb-uploader-solarweb
    environment:
      - INFLUX_ENDPOINT=${INFLUX_ENDPOINT}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
      - PYTHONUNBUFFERED=1
    volumes:
      - ${INFLUXDB_UPLOAD_CSV_DIR}:/datos
    depends_on:
      - influxdb-solarweb
  # ==========================================
  # Zerotier (Connection to the network)
  # ==========================================
  zerotier-solarweb:
    profiles: ["data", "deploy"]
    image: zyclonite/zerotier:latest
    container_name: zerotier-solarweb
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - zerotier-data:/var/lib/zerotier-one
    environment:
      - ZT_NETWORK_ID=${ZT_NETWORK_ID}
    entrypoint: >
      sh -c "
        /usr/sbin/zerotier-one -d &&
        echo 'Esperando a que el daemon se inicie...' &&
        sleep 8 &&
        zerotier-cli join ${ZT_NETWORK_ID} &&
        echo 'Unido a la red ${ZT_NETWORK_ID}, esperando...' &&
        tail -f /dev/null
      "
  # ==========================================
  # Seeder (Test data)
  # ==========================================
  seeder:
    profiles: ["test"]
    image: postgres:16
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./databases/postgres/tests_seed.sql:/seed/tests_seed.sql:ro
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}
    entrypoint: ["/bin/sh","-c"]
    command: >
       "psql -h postgres -U ${POSTGRES_USER} -d ${POSTGRES_DB} -v ON_ERROR_STOP=1 -f /seed/tests_seed.sql &&
       echo '✅ Datos de prueba cargados' || (echo '❌ Error en seed' && exit 1)"

volumes:
  influxdb2:
  miniodb2:
  postgresdb:
  zerotier-data:

networks:
  red_taller_software:
    external: false
