FROM python:3.11-slim

# Variables básicas de Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Instalar dependencias del sistema + agregar repo de ZeroTier
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    gpg \
    ca-certificates \
    build-essential \
    libpq-dev && \
    curl -s https://install.zerotier.com/ | bash && \
    rm -rf /var/lib/apt/lists/*

# Copiar e instalar dependencias de Python
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

# Copiar el código de la app
COPY . /app

# Exponer puerto del backend
EXPOSE 4002

# Crear volumen de configuración para ZeroTier
VOLUME ["/var/lib/zerotier-one"]

# Entrypoint: arranca ZeroTier + backend
CMD zerotier-one -d && \
    sleep 5 && \
    zerotier-cli join ${ZT_NETWORK_ID} && \
    sleep 5 && \
    gunicorn main:app --bind 0.0.0.0:4002 -w 1 --worker-class uvicorn.workers.UvicornWorker --log-level info
