@startuml
title Diagrama de Secuencia: Eliminar usuarios aprobados

actor Administrador
participant UI as "PAGES - usuarios"
participant FE_Service as "SERVICES - usersService"
participant ENDPOINT as "API ENDPOINT - users"
participant SERVICE as "API SERVICES - users_service"
participant SQL as "DATA PERSISTENCE - SqlAlchemy"
database DB as "POSTGRES"

== Cargar usuarios aprobados ==

Administrador -> UI : Abre página "usuarios"
UI -> FE_Service : getByStatus()
FE_Service -> ENDPOINT : GET /users/by_status?status=aprobado
ENDPOINT -> SERVICE : get_users_by_status_query(status="aprobado")
SERVICE -> SQL : Consultar usuarios con estado = 'aprobado'
SQL -> DB : SELECT * \nFROM usuarios \nWHERE estado = 'aprobado'
DB --> SQL : Query result
SQL --> SERVICE : [users]
SERVICE --> ENDPOINT : [users]
ENDPOINT --> UI : {"len": cant_usuarios, "data": [usuarios aprobados]}
UI --> Administrador : Mostrar tabla de usuarios aprobados

== Eliminar usuario aprobado ==

Administrador -> UI : Clic en "X"\nsobre un usuario aprobado

UI -> FE_Service : confirmarEliminacion()


FE_Service -> ENDPOINT : DELETE /users/delete_scheduled?usuario_id={id_usuario}

ENDPOINT -> SERVICE : mark_and_schedule_deletion_query({id})
SERVICE -> SQL : Marcar usuario como 'rechazado'
SQL -> DB : UPDATE solicitudes\nSET estado = 'rechazada'\nWHERE id = {id}
DB --> SQL : OK
SQL --> SERVICE : Confirmación de actualización
SERVICE -> SERVICE: Schedule user definitive deletion after 30 days
SERVICE --> ENDPOINT : Confirmación de rechazo

ENDPOINT --> FE_Service : 200 OK\n{usuario_actualizado}
FE_Service --> UI : Confirmar eliminación

UI -> UI : Remover usuario de la tabla\n"aprobados"
UI -> UI : Agregar usuario a la lista\n"usuarios eliminados"
UI --> Administrador : Mostrar tabla actualizada de usuarios

== Eliminación definitiva tras 30 días ==

SERVICE -> SQL : Eliminar completamente usuario tras 30 días
SQL -> DB : DELETE FROM usuarios\nWHERE id = {id} AND fecha_rechazo <= \nCURRENT_DATE - INTERVAL '30 days'
DB --> SQL : Confirmación de eliminación
SQL --> SERVICE : Confirmación de eliminación
@enduml